#%RAML 1.0
title: CardConnect Rest API
version: v1
baseUri: https://fts.cardconnect.com:6443/cardconnect/rest
securedBy: basic
securitySchemes:
  basic:
    type: Basic Authentication

protocols: [ HTTP, HTTPS ]
mediaType: [application/json, application/xml ]
uses:

types:
  type: object
  lineitem:
   properties:
    discamnt: string
    unitcost: string
    uom: string
    lineno: string
    description: string
    taxamnt: string
    quantity: string
    upc: string
    netamnt: string
    material: string

/auth:

  put:
    description: Authorize a transaction
    body:
      application/json:
        properties:
          merchid:
            required: true
          accttype: string
          orderid: string
          account: string
          expiry: string
          amount: string
          currency: string
          name: string
          address: string
          city: string
          region: string
          country: string
          postal: string
          ecomind: string
          cvv2: string
          track: string
          tokenize: string
          capture: string

    responses:
      401:
        description:
      200:
        description:
        body:
         application/json:
           properties:
             respstat: string
             account: string
             token: string
             retref: string
             amount: string
             merchid: string
             respcode: string
             resptext: string
             avsresp: string
             cvvresp: string
             authcode: string
             respproc: string
             emv: string

/capture:

 description: capture a previously authorized transaction


 put:
   body:
    application/json:

      properties:
        retref: string
        merchid: string
        authcode: string
        amount: string
        invoiceid: string
        ponumber: string
        taxamnt: integer

   responses:
    401:

    200:
      description:  Hi
      body:
        application/json:
          properties:
            respproc: string
            amount: string
            resptext: string
            setlstat: string
            commcard: string
            retref: string
            respstat: string
            respcode: string
            batchid: string
            account: string
            merchid: string
            token: string

/void:
  description: void a previously authorized transaction

  put:
    body:
     application/json:

       properties:
         retref: string
         merchid: string
         amount: string

    responses:
      401:
      200:
        body:
          application/json:
            properties:
              merchid: string
              amount: string
              currency: string
              retref: string
              authcode: string
              respcode: string
              respproc: string
              respstat: string
              resptext: string

/refund:
  description: refund a previously captured transaction

  put:
    body:
     application/json:

       properties:
         retref: string
         merchid: string
         amount: string

    responses:
      401:

      200:
        body:
          application/json:
            properties:
              amount: string
              resptext: string
              authcode: string
              respcode: string
              retref: string
              merchid: string
              cvvresp: string
              account: string
              avsresp: string
              respproc: string
              respstat: string

/inquire:

  description: inquire about a transaction

  put:
    body:
     application/json:

       properties:
         retref: string
         merchid: string

    responses:
      401:

      200:
        body:
          application/json:
            properties:
              amount: string
              resptext: string
              setlstat: string
              capturedate: string
              respcode: string
              batchid: string
              merchid: string
              token: string
              respproc: string
              authdate: string
              lastfour: string
              name: string
              currency: string
              retref: string
              respstat: string
              account: string


/setlstat:

  description: settlment batch information

  get:
    description: retrieve all settlement batches by date for merchant

    queryParameters:
        merchid:
          type: string
        date:
          type: date-only

    responses:
      401:

      200:
        body:
          application/json:
            properties:
              respproc: string
              hostbatch: string
              refundtotal: string
              batchid: string
              chargetotal: string
              hoststat: string
              merchid: string

/funding:

  description: provide bank deposit data

  get:

    description: retrieve all bank deposits by date for merchant

    queryParameters:
        merchid:
          type: string
        date:
          type: string

    responses:
      200:
        body:
          application/json:
            properties:
              cardtype: string
              status: string
              retref: string
              interchangeunitfee: string
              cardnumber: string
              type: string
              fundingid: number
              interchangepercentfee: number
              date: string
              currency: string
              cardbrand: string
              amount: number
              fundingtxnid: number



/profile:

  description: card on file service

  get:

    description: retrieve a profile and either 1 or all accounts

    queryParameters:
      profileid:
        type: string
      acctid:
        type: string
      merchid:
        type: string

    responses:
      200:
        body:
          application/json:
            properties:
              region: string
              postal: string
              address: string
              accttype: string
              token: string
              name: string
              license: string
              country: string
              city: string
              expiry: string
              profileid: string
              acctid: string


  put:
      description: create a profile

      body:
        application/json:

          properties:

            merchid: string
            accttype: string
            account: string
            expiry: string
            name: string
            address: string
            city: string
            region: string
            country: string
            phone: string
            postal: string
            ssnl4: string
            license: string

      responses:
        200:
          body:
            application/json:
              properties:


  delete:
    description: delete a profile

    queryParameters:
        profileid:
          type: string
        acctid:
          type: string
        merchid:
          type: string

    responses:
      401:

      200:
        body:
          application/json:
            properties:
              respcode: string
              resptext: string
              profileid: string
              acctid: string
              respproc: string
              respstat: string

/sigcap:
  put:
    description: save a signature image

    body:
      application/json:
        properties:
          merchid: string
          retref: string
          signature: object

    responses:
      200:
        body:
          application/json:
            properties:



/openbatch:
  get:
    description: create new settlement batch

    queryParameters:

      merchid:
        type: string
      batchsource:
        type: string

    responses:
      200:
        body:
          application/json:
            properties:
              batchid: string
              respcode: string

/closebatch:
    get:
      description: close a previously opened settlement batch

      queryParameters:
        merchid:
          type: string
        batchsource:
          type: string

      responses:
        200: # HTTP STatus Code
          body:
            application/json:
              properties:
                batchid: string
                respcode: string
              example: |
                {
                  "batchid":"2628",
                  "respcode":"success"
                  }


/bin:
  get:
    description: retrieve BIN information for a given token
    queryParameters:
       merchid: string
       token: string
    responses:
      200:
        body:
          application/json:
            properties:
               country: string
               product: string
               cardusestring: string
               gsa: boolean
               corporate: boolean
               fsa: boolean
               subtype: string
               purchase: boolean
               prepaid: boolean
               binlo: string
               issuer: string
               binhi: string
